### ISSUE TITLE
Just Stop Working

### ISSUE THREAD

**Issue by paisabordo** [2captcha/2captcha-java#3]
I've been working without problems until today.

Same application, without any code change since 10/30/2020.

Now every single request I receive this exceptions .

#### 2CAPTCHA CHAMADO #####
com.twocaptcha.exceptions.ApiException: ERROR_ZERO_CAPTCHA_FILESIZE
	at com.twocaptcha.ApiClient.execute(ApiClient.java:100)
	at com.twocaptcha.ApiClient.in(ApiClient.java:59)
	at com.twocaptcha.TwoCaptcha.send(TwoCaptcha.java:212)
	at com.twocaptcha.TwoCaptcha.solve(TwoCaptcha.java:154)
	at com.twocaptcha.TwoCaptcha.solve(TwoCaptcha.java:142)
	at com.mueller.pregaobot.parser.ConsultaAtaPage.captchaScreen(ConsultaAtaPage.java:276)
	at com.mueller.pregaobot.parser.ConsultaAtaPage.listaScreen(ConsultaAtaPage.java:121)
	at com.mueller.pregaobot.parser.ConsultaAtaPage.search(ConsultaAtaPage.java:84)
	at com.mueller.pregaobot.Main$2.lambda$actionPerformed$0(Main.java:153)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
ERRO AO INVALIDAR CAPTCHA
CAPTCHA INVÁLIDO. INFORME NOVAMENTE.
#### 2CAPTCHA CHAMADO #####
com.twocaptcha.exceptions.ApiException: Cannot recognise api response (TOO_MANY_BAD_IMAGES)
	at com.twocaptcha.TwoCaptcha.send(TwoCaptcha.java:215)
	at com.twocaptcha.TwoCaptcha.solve(TwoCaptcha.java:154)
	at com.twocaptcha.TwoCaptcha.solve(TwoCaptcha.java:142)
	at com.mueller.pregaobot.parser.ConsultaAtaPage.captchaScreen(ConsultaAtaPage.java:276)
	at com.mueller.pregaobot.parser.ConsultaAtaPage.listaScreen(ConsultaAtaPage.java:121)
	at com.mueller.pregaobot.parser.ConsultaAtaPage.search(ConsultaAtaPage.java:84)
	at com.mueller.pregaobot.Main$2.lambda$actionPerformed$0(Main.java:153)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

**Comment by kratzky** [comment]
See [Error handling](https://2captcha.com/2captcha-api#error_handling)
