### ISSUE TITLE
Don't work

### ISSUE THREAD

**Issue by Jinthium** [2captcha/2captcha-java#8]
Exception in thread "main" java.lang.NoClassDefFoundError: okhttp3/RequestBody
	at com.twocaptcha.TwoCaptcha.<init>(TwoCaptcha.java:66)
	at com.twocaptcha.TwoCaptcha.<init>(TwoCaptcha.java:75)
	at Main.main(Main.java:96)
Caused by: java.lang.ClassNotFoundException: okhttp3.RequestBody
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:636)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:182)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:519)
	... 3 more

**Comment by kratzky** [comment]
Please if you need help - provide your code or describe how to reproduce your issue.
